import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";
import { AudioProvider } from "./components/Providers/AudioProvider";
import AudioPlayerBar from "./components/AudioPlayerBar/AudioPlayerBar";
import { AuthProvider } from "./components/Providers/AuthContext/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Podcast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <AudioProvider> {/* Wrap the children with AudioProvider */}
        <div className="flex flex-col ">
          <Navbar />
          <div className="flex flex-shrink-0  flex-1">
            {/* Sidebar */}
            <Sidebar />

            {/* Main Content */}
           
            <div className="main-content  pl-2 pr-2 ">
            <AuthProvider>
                {children}
              </AuthProvider> 
            </div>
          </div>
          <AudioPlayerBar />
        </div>
        </AudioProvider>
      </body>
    </html>
  );
}
