import type { Metadata } from "next";
import "./globals.css";
import { AudioProvider } from "./components/Providers/AudioProvider";
import { AuthProvider } from "./components/Providers/AuthContext/AuthContext";
import { PlaylistProvider } from "./components/Providers/PlaylistContext";
import { Toaster } from "react-hot-toast";
import LayoutContent from "./layoutContent";

export const metadata: Metadata = {
  title: "Podcast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AudioProvider>
            <PlaylistProvider>
              <Toaster
                position="bottom-center"
                reverseOrder={true}
                toastOptions={{
                  style: { marginBottom: "60px" },
                }}
              />
              <LayoutContent>{children}</LayoutContent>
            </PlaylistProvider>
          </AudioProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
