import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";
import { AudioProvider } from "./components/Providers/AudioProvider";
import AudioPlayerBar from "./components/AudioPlayerBar/AudioPlayerBar";
import { AuthProvider } from "./components/Providers/AuthContext/AuthContext";

export const metadata: Metadata = {
  title: "Podcast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Wrap the entire layout with both providers */}
        <AuthProvider>
          
            <AudioProvider>
              <div className="flex flex-col ">
                <Navbar />
                <div className="flex flex-shrink-0 pl-2 flex-1 ">
                  {/* Sidebar */}
                  <Sidebar />

                  {/* Main Content */}
                  <div className="main-content pl-2 pr-2">{children}</div>
                </div>
                <AudioPlayerBar />
              </div>
            </AudioProvider>
          
        </AuthProvider>
      </body>
    </html>
  );
}
